[package]
name = "bullet"
version = "0.1.0"
authors = ["Daniel Parker <danpker@gmail.com>"]

[dependencies]
chrono = "0.4"
clap = "2.30.0"
dirs = "1.0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
